### ISSUE TITLE
Measurement is confused with bucket

### ISSUE THREAD

**Issue by Illutax** [TwentyFiveSoftware/influxql2flux#2]
In InfluxQL the `FROM` is followed by the measurement. The influxql2flux translates it to bucket name, which is (sometimes?) wrong.

Consider following InfluxQL query:

```
SELECT min("value") FROM "health_status" WHERE $timeFilter GROUP BY time($interval), "environment_name", "component_name" fill(null)
```

influxql2flux returns:
```
from(bucket: "health_status")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._field == "value")
  |> group(columns: ["environment_name", "component_name"], mode: "by")
  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)
  |> keep(columns: ["_time", "_value", "environment_name", "component_name"])
  |> sort(columns: ["_time"])
```

In our case, we have a bucket named `app`  so I would expect the bucket also to be `app`.
I know it is not present in the InfluxQL, but a more resonable default would be
```
from(bucket: "<bucket_name>")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "health_status")
  ...
````

**Comment by TwentyFiveSoftware** [comment]
You are absolutely right. As stated in the [documentation](https://docs.influxdata.com/influxdb/v1.3/query_language/data_exploration/#from-clause), a single identifier in the from clause should be interpreted as the measurement name rather than the database name. This issue is fixed [now](https://github.com/TwentyFiveSoftware/influxql2flux/commit/cc038afa944d885a02ae03cd167dd2755e26598e).
